---
name: Deploy Infrastructure-Development

on: 
  workflow_dispatch:

jobs:
  deploy-infra-env:
    uses: ./.github/workflows/DeployInfra.yml
    with:
      environment: development
    secrets: inherit
...