---
name: Destroy Infrastructure-Development

on: 
  workflow_dispatch:

jobs:
  destroy-infra-env:
    uses: ./.github/workflows/DestroyInfra.yml
    with:
      environment: development
    secrets: inherit
...