---
name: Lint Workflows

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - 'feature/*'
      - 'fix/*'
      - 'release/*'
    paths:
      - '.github/workflows/**'
  pull_request:
    branches:
      - develop
      - main
      - 'release/*'
    paths:
      - '.github/workflows/**'

jobs:
  lint_workflows:
    name: Lint Workflows
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Workflows
        uses: github/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: develop
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_INCLUDE: .*.github/workflows/.*
...